services:
  app:
    build: .
    ports:
      - "5175:8080"    # 宿主机5175端口映射到容器8080端口(Go应用)
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "5176:80"      # 宿主机5176端口映射到容器80端口(Nginx)
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: always

networks:
  todolist-network:
    driver: bridge

volumes:
  data: